### ISSUE TITLE
LSP-volar exited with status code -32603.

### ISSUE THREAD

**Issue by NewStorm-0** [sublimelsp/LSP-volar#109]
**System Info**:
- Windows 10 Professional 21H2
- Sublime Text Stable channel, Build 4113
- LSP v1.16.3
- LSP-volar v1.0.19
- Vue Syntax Highlight v4.0.1

<img width="287" alt="111" src="https://user-images.githubusercontent.com/81554959/181700228-c490ed49-b79c-46ff-be9e-57ff80ed2f90.png">
After I installed the three plugins following the steps in the readme file, I restarted sublime text. I haven't done any action yet and this error appears. I tried to click the button "**Restart LSP-volar**" , but nothing works. The error happened again in 1 second.

**Comment by rchl** [comment]
You can run `LSP: Troubleshoot server` from the command palette and provide its output

**Comment by NewStorm-0** [comment]
# Troubleshooting: LSP-volar
## Version
 - LSP: 1.16.3
 - Sublime Text: 4113
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh
E:\Node_js\node.EXE "F:\Sublime Text\Data\Package Storage\LSP-volar\16.15.0\server\node_modules\@volar\vue-language-server\bin\vue-language-server.js" --stdio
```
 - selector
```
text.html.vue
```
 - priority_selector
```
(text.html.vue)
```
 - init_options
```json
{
  "typescript": {}
}
```
 - settings
```json
{
  "volar": {
    "autoCompleteRefs": false, 
    "autoWrapParentheses": true, 
    "codeLens": {
      "pugTools": false, 
      "references": true, 
      "scriptSetupTools": false
    }, 
    "completion": {
      "autoImportComponent": true, 
      "preferredAttrNameCase": "auto-kebab", 
      "preferredTagNameCase": "auto"
    }, 
    "vueserver": {
      "maxOldSpaceSize": null
    }
  }
}
```
 - env
```json
{
  "PATH": "E:\\Node_js;E:\\Node_js;E:\\Node_js;E:\\Node_js;"
}
```

## Active view
 - File name
```
E:\School\数据库\数据库课程设计\supermarket\src\App.vue
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/Vue Syntax Highlight/Vue Component.sublime-syntax"
}
```
 - base scope
```
text.html.vue
```

## Project / Workspace
 - folders
```json
[]
```
 - is project: False

## LSP configuration

<not found>
## System PATH
 - F:\VMwareWorkstationPro16\bin\
 - C:\Program Files (x86)\Intel\iCLS Client\
 - C:\Program Files\Intel\iCLS Client\
 - C:\Windows\system32
 - C:\Windows
 - C:\Windows\System32\Wbem
 - C:\Windows\System32\WindowsPowerShell\v1.0\
 - C:\Windows\System32\OpenSSH\
 - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
 - C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
 - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
 - C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
 - C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
 - C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
 - F:\Microsoft VS Code\bin
 - F:\Maven\apache-maven-3.8.3\bin
 - C:\Program Files\MySQL\MySQL Server 8.0\bin
 - C:\Program Files (x86)\Common Files\Thunder Network\KanKan\Codecs
 - F:\SQLite
 - F:\Qt\6.2.3\msvc2019_64\bin
 - f:\quartusii9.0\quartus\bin
 - C:\Program Files\Java\jdk-17.0.1\bin
 - C:\Program Files\Java\jdk-17.0.1\jre\bin
 - F:\Gradle\bin
 - F:\texlive\2022\bin\win32
 - E:\Node_js\
 - C:\Program Files\dotnet\
 - F:\Git\cmd
 - F:\gs9.56.1\bin
 - C:\Program Files\PowerShell\7\
 - F:\MATLAB\runtime\win64
 - F:\MATLAB\bin
 - F:\MATLAB\polyspace\bin
 - C:\Program Files\MySQL\MySQL Shell 8.0\bin\
 - C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\
 - C:\Users\Administrator\AppData\Local\Programs\Python\Python39\
 - C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps
 - F:\IntelliJ IDEA Community Edition 2021.1.3\bin
 - F:\PyCharm 2021.1.1\bin
 - E:\c1\新建文件夹\版本烧录工具及方法\PhoenixSuitV1.10\
 - C:\Users\Administrator\.dotnet\tools
 - %WebStorm%
 - F:\IntelliJ IDEA 2021.1.3\bin
 - 
 - C:\Users\Administrator\AppData\Roaming\npm
 - C:\Users\Administrator\.dotnet\tools

**Comment by rchl** [comment]
You can try adding the `E:\School\数据库\数据库课程设计\supermarket\` folder to the side panel and then trying opening one of the VUE files within it.

**Comment by NewStorm-0** [comment]
Thang you very much. It worked!!!😊
It's all good now, but the speed of _Indexing Files_ is very slow.🤣

**Comment by rchl** [comment]
You can raise and discuss such issues in https://github.com/johnsoncodehk/volar.
