### ISSUE TITLE
The auto complete triggers are way too aggressive

### ISSUE THREAD

**Issue by FichteFoll** [sublimelsp/LSP-volar#114]
With volar, the AC popup opens way too frequently, most notably after inserting a comma. I noticed that the following gets added to my `auto_complete_triggers` setting:

```
{'characters': '!@#$%^&*()_+-=`~{}|[]:";\'<>?,./ ', 'selector': 'source - comment - string, meta.tag - punctuation.definition.tag.begin', 'server': 'LSP-volar'}
```
(https://github.com/johnsoncodehk/volar/blob/b3b30931080b3f377e8f33dbb4808fe216c7763a/packages/vue-language-server/src/registers/registerlanguageFeatures.ts#L59-L59)

I really only want to have auto completion after a period, so basically what the default settings already do via `{"selector": "punctuation.accessor", "rhs_empty": true}`. 

I adopted the following section from the LSP-json plugin locally for me: 

https://github.com/sublimelsp/LSP-json/blob/a65342f9908b0a759c148a574815d20811201b06/LSP-json.sublime-settings#L16-L21

**Comment by rchl** [comment]
It doesn't seem like VSCode triggers completions on comma, for example, even when the server returns same trigger characters.

@johnsoncodehk do you know why this wouldn't affect VSCode and why such choice of trigger characters?

**Comment by johnsoncodehk** [comment]
All valid trigger character is collect from embedded language service plugin, but it cannot know at register language server features in advance, so vue language server config all characters and divert trigger character completion request itself.

If this causes problems, I can remove characters such as ',' for now.

- https://github.com/johnsoncodehk/volar/blob/d4fd1ba108bb2d4bc1caf034bb94d22167cbb4de/packages/vue-language-service/src/plugins/css.ts#L47
- https://github.com/johnsoncodehk/volar/blob/d4fd1ba108bb2d4bc1caf034bb94d22167cbb4de/packages/vue-language-service/src/plugins/typescript.ts#L41-L45
...

**Comment by rchl** [comment]
If those trigger characters do nothing for VSCode (not sure what is its logic) and causes problems in other editors then removing would make sense IMO.

**Comment by johnsoncodehk** [comment]
Please try v0.40.4.

**Comment by rchl** [comment]
Released in https://github.com/sublimelsp/LSP-volar/releases/tag/v1.1.0

**Comment by FichteFoll** [comment]
Fix confirmed. 

There still appears to be a rather large set of completion triggers (like `()[]-`), but I wasn't able to get them to misbehave in contexts where I wouldn't expect completions to show.

**Comment by johnsoncodehk** [comment]
You can config `initializationOptions.languageFeatures.completion.ignoreTriggerCharacters` to filter completion trigger characters that you don't wanted with v0.40.7.
