### ISSUE TITLE
Latest release is broken (view contents go out of sync?)

### ISSUE THREAD

**Issue by FichteFoll** [sublimelsp/LSP-volar#120]
After updating to 1.1.0, I've encountered several serious problems. Following is a probably incomplete list:

- Highlighted regions go out of sync all the time when editing the file.
  ![2022-08-30_14-18-30](https://user-images.githubusercontent.com/931051/187460428-d1267851-2814-4be4-9817-8e6c74bab532.png)
(expected: blue line under the `assigned-brands` class and orange under `anchor-tooltip`)

- Some error marks are simply wrong and incorrect, e.g. a tag supposedly not being closed. My theory is that they were valid at some point in the edit history and have long since been fixed, but LSP still marks them until I close and re-open the view. And they keep accumulating.

- "0 references" code lens shown on CSS properties (?)
  ![2022-08-30_13-45-52](https://user-images.githubusercontent.com/931051/187460652-1306b733-1cb2-48a6-8682-b9690a13e494.png)

**Comment by rchl** [comment]
I feel that those kind of issues could be reported directly in the volar repo sine we can't do much about those here (besides reverting to an older version).

But for now gonna ping @johnsoncodehk

**Comment by johnsoncodehk** [comment]
It should be fixed by https://github.com/johnsoncodehk/volar/commit/e2090ee52f95c5ec1abb83bff2b489730f897acf.

**Comment by johnsoncodehk** [comment]
Please try @volar/vue-language-server v0.40.5.

**Comment by ElMassimo** [comment]
Thanks Johnson, can confirm that `v0.40.5` fixes the issue 😃

**Comment by rchl** [comment]
https://github.com/sublimelsp/LSP-volar/releases/tag/v1.1.1
