### ISSUE TITLE
LSP-Volar stops working (Possibly Node version issue?)

### ISSUE THREAD

**Issue by Hobstweedl** [sublimelsp/LSP-volar#164]
I'm installing Sublime Text, LSP and LSP-volar on a new mac, and finding that the plugin seems to start to initialize and then stop working, no features such as inlay hints, autocompletion, or warnings/error appear. 

I've been able to verify that `lsp-eslint` works fine, `lsp-typescript` seems to show me errors in the IDE but inlay hints do not work at all. I have a second older macbook with LSP and ST at the same versions and same configurations and everything works fine. The only difference in setups I can think of is that the older macbook has Node set at `v16.13.2` and this new mac is `v18.4.0`. I haven't been able to find any indicator in the console or logs that anything is failing, it just seems like at a certain point `lsp-volar` just stops working and turns off. Details attached below, I'm unsure of what else I could provide that would be helpful

[log.txt](https://github.com/sublimelsp/LSP-volar/files/10786559/log.txt)
[Troubleshooting.md](https://github.com/sublimelsp/LSP-volar/files/10786560/Troubleshooting.md)

**Comment by rchl** [comment]
You can easily test with bundled Node 16 by opening `Preferences: LSP Utils Settings` from the command palette and settting

```
{
  "nodejs_runtime": ["local"],
}
```

**Comment by rchl** [comment]
It does look like Volar silently exists soon after starting but there doesn't seem to be anything wrong with the settings so it's either Node version or something in the project if I'd to guess.

**Comment by Hobstweedl** [comment]
Switching to the local runtime does fix the issue. I guess there's some breaking change in latest Node that affects LSP. Thanks!

**Comment by rchl** [comment]
I suppose we can at least set a restriction on node version so that the error message is clear when using v18. Have to try it out here when I have some time.

**Comment by rchl** [comment]
I've tried `18.4.0` and latest `18.16.1` and both worked fine. It might be some incompatibility with the dependencies in your project. Are you able to share your project or create minimal repo that reproduces?
