### ISSUE TITLE
Failed resolving Node.js Runtime. Please check in the console for more details.

### ISSUE THREAD

**Issue by Mrceel** [sublimelsp/LSP-volar#181]
Could not start LSP-volar due to not being able to resolve suitable Node.js runtime on the PATH. Press the "Download Node.js" button to get required Node.js version (note that it will be used only by LSP and will not affect your system otherwise).

--- Error: ---
Failed resolving Node.js Runtime. Please check in the console for more details.

我已经通过nvm安装了nodejs

**Comment by predragnikolic** [comment]
@Mrceel,
Did you managed to resolve your issue?

**Comment by predragnikolic** [comment]
Some node language servers require a specific version of node to be installed, in order to function properly.

My best suggestion for you is to just press the "Download Node.js" button,
that will install the node version that should work with most of the servers for now.
