### ISSUE TITLE
Error rewriting command lsp_recheck_sessions. Encountered infinite loop

### ISSUE THREAD

**Issue by Shuzhenzhou** [sublimelsp/LSP-volar#185]
Error rewriting command lsp_recheck_sessions. Encountered infinite loop

LSP: LSP-volar crashed (1 / 5 times in the last 180.0 seconds), exit code 1, exception: None
LSP: LSP-volar crashed (2 / 5 times in the last 180.0 seconds), exit code 1, exception: None
LSP: LSP-volar crashed (3 / 5 times in the last 180.0 seconds), exit code 1, exception: None
LSP: LSP-volar crashed (4 / 5 times in the last 180.0 seconds), exit code 1, exception: None
LSP: LSP-volar crashed (5 / 5 times in the last 180.0 seconds), exit code 1, exception: None

**Comment by rchl** [comment]
`lsp_recheck_sessions. Encountered infinite loop` is not an issue and is unrelated to the crash.

As for the crash, check the output after running LSP: Toggle Log Panel command

**Comment by Shuzhenzhou** [comment]
ok , thank; but logs print  SyntaxError: Unexpected token '??=' what should I do

**Comment by Shuzhenzhou** [comment]
![image](https://github.com/sublimelsp/LSP-volar/assets/46117922/6b71a399-2c0c-4dfb-9e01-6d4db3b4a7aa)

**Comment by Shuzhenzhou** [comment]
Do I need to change it one by one？

**Comment by predragnikolic** [comment]
It looks like your global version of node is 14.21.3.

there are two options I can suggest:
a) You could install a newer version of node, for example 16. This option affects your system.
 
b)From the command palette select: `Preference: LSP Utils Settings` and set the following in lsp_utils.sublime-settings:
```
{
    "nodejs_runtime": ["local"],
}
```
That will download a local  Node 16.15.0(by local, it will not mess with your global node version) for LSP-* based plugins
in sublime caches folder(on window that path should be %LocalAppData%/Sublime Text).

**Comment by Shuzhenzhou** [comment]
thanks
