### ISSUE TITLE
LSP needs restart to be up-to-date with *.ts imports

### ISSUE THREAD

**Issue by brachkow** [sublimelsp/LSP-volar#205]
LSP needs restart to be up-to-date with *.ts imports.

If I import something from *.ts file into Vue, and then edit — LSP will show me outdated information until I restart it via command palette.

**Comment by brachkow** [comment]
Oh, I found mention of this in README — https://github.com/vuejs/language-tools/issues/3229

**Comment by rchl** [comment]
Yes, upstream issue.
