### ISSUE TITLE
Adapt to typescript-plugin approach

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-volar#221]
New version of Vue Language Tools is implemented using a typescript plugin rather than standalone server. We should support that approach.

(We shouldn't need to rush since it will take some time for it to iron out new issues)

Some ways of handling it:
1) Let user use LSP-typescript and manually set up the plugin per project
2) Bundle VLT plugin with LSP-typescript
3) Support some way of auto-registering plugins with LSP-typescript so that it's possible for this package to register the plugin automatically when installed. (Q: will it be OK to enable the plugin even for non-vue projects or could it cause issues?)
4) Like 3 but using a separate "LSP-typescript-vue-plugin" package (or whatever would be the appropriate name)

**Comment by niksy** [comment]
Is there any ETA when can we expect this?

It seems like [issue with changes in related files](https://github.com/sublimelsp/LSP-volar/issues/205) is fixed with TS plugin approach.

**Comment by rchl** [comment]
As far as I understand, the plugin only handles standalone `.ts/.js` files and the `script` block within `vue` files. For the rest of the functionality (like `style` and some of the functionality in the `template` blocks) you still need to run the 2.x "volar" server.

So I'm not sure how we should go about it. Whether having LSP-volar should configure LSP-typescript plugin behinds the scenes or should we put that responsibility on the user by editing `tsconfig` or project settings (and maybe provide some helper commands to make that semi-automatic)...

**Comment by niksy** [comment]
> As far as I understand, the plugin only handles standalone .ts/.js files and the script block within vue files. For the rest of the functionality (like style and some of the functionality in the template blocks) you still need to run the 2.x "volar" server on top of that.

Yes, that is correct. Both LSPs need to be active for Vue files, hence the `selector` field adjustments. I think this new approach is basically about reducing memory consumption between running multiple TS server instances and simplification of codebase on Volar side.

> So I'm not sure how we should go about it. Whether LSP-volar should configure LSP-typescript plugin behind the scenes or should we put that responsibility on the user by editing tsconfig or project settings (and maybe provide some helper commands to make that semi-automatic)...

Completely automatic feels magical if it means that user-specific LSP-typescript settings get changed, I just think it would look weird if users settings get changed without any information (maybe some comment inside settings which explain why the change is there). If it can be done without user knowing that initialization options are changed then I think it’s good. Otherwise, helper seems okay approach, and even instructions in documentation are OK, but it’s definitely something power users know.

Are there any similar examples of these kind of changes?

**Comment by dten** [comment]
I'm trying @niksy fork and have it working with by using the snippet above. However... is it just me or does getting that path to that node_modules dir really suck? I've ended up with an absolute path that includes a version number. If users had to fix that every time the plugin updated that would be painful.

`/home/david/.cache/sublime-text/Package Storage/LSP-volar-next/20.12.2/server/node_modules/node_modules/@vue/typescript-plugin`

**Comment by dten** [comment]
btw i started looking at Vue 3.5's `useTemplateRef` does not figure out its own type in the current `LSP-volar`

**Comment by niksy** [comment]
Yes, unfortunately you need to use absolute path to plugin.

This could definitely be solved at LSP client level as mentioned by @rchl:

> Whether LSP-volar should configure LSP-typescript plugin behind the scenes or should we put that responsibility on the user by editing tsconfig or project settings (and maybe provide some helper commands to make that semi-automatic)...

**Comment by dten** [comment]
I've only been using it a few hours but everything seems fine so far

**Comment by rchl** [comment]
https://github.com/sublimelsp/LSP-vue now runs on latest version of Vue Language Server so I would consider this resolved even if it's currently not using the plugin approach.

I intend to get the plugin approach (hybrid mode) support but currently it's a bit trickly for few reason listed in https://github.com/sublimelsp/LSP-vue/issues/130
