### ISSUE TITLE
Volar doesn't provide any completions etc.

### ISSUE THREAD

**Issue by Bocom** [sublimelsp/LSP-volar#38]
**System info**
Windows 10 21H1
Sublime Text 4 (4113)
Node 14.17.6 (through [Volta](https://volta.sh/), but regular Node doesn't work either and other Node-based language servers (like LSP-vue and LSP-typescript) do work)
LSP 1.12.1
LSP-volar 1.0.3

**Issue**
Volar doesn't return any completions or much of anything, the only thing that works is formatting files.
When looking at the language server debug log, it just returns some combinations of empty arrays or `None` regardless of what's being done (aside from formatting, as previously mentioned), as can bee seen in the attached language server log.

Of note, during initialization, a blank `cmd.exe` window running `node.exe` pops up for a split second before it's gone. This doesn't happen with the other Node-based language servers I use.

**Logs**
Here is the system log:
[system.log](https://github.com/sublimelsp/LSP-volar/files/7324378/system.log)

And here is the language server log:
[langserver.log](https://github.com/sublimelsp/LSP-volar/files/7331160/langserver.log)

**Comment by predragnikolic** [comment]
I compared your logs with mine, and they seem to look good.

Just to cross node.js as a potental problem, 
can you try this?

From the command palette, select `Preferences: LSP Utils settings`.
and paste this:

```
{
	"nodejs_runtime": ["local"],
}
```
Restart ST.
You should see this window.

![image](https://user-images.githubusercontent.com/22029477/137298506-00497006-8a52-4053-a0a6-9d32ce123f02.png)

Select `Install Node.js`. LSP will automatically install the Node Runtime locally(Node V14.17.6 will be installed at the time of writing). It won't install Node globally.

After Node is installed, restart ST just in case, (i don't think it is necessary but it will not hurt) :)
Open a vue file and see if it working?

**Comment by Bocom** [comment]
I tried doing that just now and unfortunately, it didn't work, the results are the same (i.e. only formatting works).

Truncated system log (for posterity's sake)
```
LSP: Resolved Node Runtime for client LSP-volar: NodeRuntimeLocal(node: C:\Users\Bocom\AppData\Local\Sublime Text\Package Storage\lsp_utils\node-runtime\14.17.6\node\node.exe, npm: C:\Users\Bocom\AppData\Local\Sublime Text\Package Storage\lsp_utils\node-runtime\14.17.6\node\node_modules\npm\bin\npm-cli.js, version: 14.17.6)
LSP: starting ['C:\\Users\\Bocom\\AppData\\Local\\Sublime Text\\Package Storage\\lsp_utils\\node-runtime\\14.17.6\\node\\node.exe', 'C:\\Users\\Bocom\\AppData\\Local\\Sublime Text\\Package Storage\\LSP-volar\\14.17.6\\server\\node_modules\\@volar\\server\\out\\index.js', '--stdio'] in C:\Projekt\temp\volar-repro
LSP: LSP-volar: Supported execute commands: ['volar.server.executeConvertToKebabCase', 'volar.server.executeConvertToPascalCase']
LSP: LSP-volar: supported code action kinds: ['', 'quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source', 'source.fixAll', 'source.organizeImports']
LSP: LSP-volar: registering capability: didChangeConfigurationProvider
```

**Comment by predragnikolic** [comment]
I have setup window 10 and I can reproduce the issue.

**Comment by predragnikolic** [comment]
We had issues like this with other servers as well:

https://github.com/vuejs/vetur/issues/1316
https://github.com/vuejs/vetur/issues/2433

**Comment by Bocom** [comment]
Ironically, that second issue (https://github.com/vuejs/vetur/issues/2433) is based on an issue of mine for LSP-vue (https://github.com/sublimelsp/LSP-vue/issues/83).
Figures that it's another silly Windows/VS Code interaction. 😅 

I guess the solution in the case of Vetur was to modify upstream to make it work "properly", presumably that's what should happen here too?
