### ISSUE TITLE
Thank you for the package

### ISSUE THREAD

**Issue by kiaking** [sublimelsp/LSP-volar#86]
Hi, sorry bother you. I don't have any issue. But I had to speak out roud.

Thank you so much for the package!!! You have no idea how happy I am to find this out. Full respect and graditude to you.

YOU ARE THE BEST 🍻 

Please close this issue. I just wanted to tell this.

**Comment by predragnikolic** [comment]
It is always nice to see comments like this!
@johnsoncodehk is the one doing the hard work 🙂
